### ISSUE TITLE
No Connection problem on Chrome browser

### ISSUE THREAD

**Issue by ArsalRaza** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#176] opened 2015-12-03 18:10 UTC
Hi guys,
   I have an issue with Branch sdk. The issue is that when I clicked on any URL (generated generated by Branch sdk), it works fine on HTC One X (API: 17) but when I tried the same link on Note 5, HTC E8 or any other device having an android version greater than API: 18, it shows me the error on chrome browser `No Connection found` on chrome browser and if I use any other browser, it open the application in play store instead of open the application in the mobile.

**Comment by sojanpr** [comment] 2015-12-03 18:32
@ArsalRaza Thanks for reaching out. We are  trying to reproduce this issue , even though we have it working properly on the test device. Will update asap on this

**Comment by ArsalRaza** [comment] 2015-12-03 18:39
@sojanpr thanks for concerning in this issue, I am getting this from last 2 weeks...!

**Comment by Sarkar** [comment] 2015-12-03 18:41
@ArsalRaza thanks for bringing it to our attention. In order to make sure we have everything, could you also email this to support@branch.io? thanks, we'll be sure to update the issue here when we figure it out

**Comment by sojanpr** [comment] 2015-12-11 08:30
@ArsalRaza are you seeing this issue any more. If not can we close this issue

**Comment by sojanpr** [comment] 2015-12-16 17:53
Closing this issue since not able to reproduce

**Closed by sojanpr** 2015-12-16 17:53 UTC
