### ISSUE TITLE
"+clicked_branch_link":false all the time

### ISSUE THREAD

**Issue by dbystVF** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#129] opened 2015-09-06 15:42 UTC
Manifest:

     <activity
            android:name=".activity.LoginScreen"
            android:label="@string/app_name"
            android:windowSoftInputMode="adjustResize"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <data android:scheme="myscheme" android:host="open" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>
        <meta-data android:name="io.branch.sdk.TestMode" android:value="true" />
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_my_key" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_my_key" />

Custom Application class:

      public class MyApplication extends MultiDexApplication {
           @Override
           public void onCreate() {
           super.onCreate();

           Branch.getAutoInstance(this);
     }

And login screen:

    @Override
    protected void onStart() {
        super.onStart();

        Branch branch = null;
        try {
            branch = Branch.getInstance();
        } catch (BranchException e) {
            e.printStackTrace();
        }
        final Branch finalBranch = branch;
        branch.initSession(new Branch.BranchReferralInitListener() {
            @Override
            public void onInitFinished(final JSONObject jsonObject, final BranchError branchError) {
                Log.v("params", jsonObject.toString());
            }
        }, this.getIntent().getData(), this);
    }

    @Override
    public void onNewIntent(Intent intent) {
        this.setIntent(intent);
    }

And here is the issue, case is next:
1. App is closed
2. User click on branch link
3. App opening, Login screen starts
4. in onInitFinished callback I always got next params:
{"+is_first_session":false,"+clicked_branch_link":false}

Why clicked branch_link = false ? I'm clicking on link...What I missed ?

Thanks,
Dmytro

**Comment by sojanpr** [comment] 2015-09-08 17:15
@dbystVF Thanks for reaching out and really sorry for the issue you are facing. We are trying to recreate and fix the issue. Could you please help us with the following to debug the issue
1.`Force close` the app from your setting
2.Launch the app by clicking  a Branch link

**Comment by dbystVF** [comment] 2015-09-08 17:32
@sojanpr  Thanks for response. Just did your steps. Result the same

**Comment by sojanpr** [comment] 2015-09-08 17:54
@dbystVF Thanks for trying it. We  are working on it and update you soon.

**Comment by derrickstaten** [comment] 2015-09-08 20:10
@dbystVF can you send an email to support@branchmetrics.io with your Branch Key and a link to this issue? We want to dig into our logs to see if we can discover the issue.

**Comment by dbystVF** [comment] 2015-09-08 20:11
@derrickstaten Sure, in a minute. Thx

**Comment by sojanpr** [comment] 2015-09-09 17:23
Closing this issue since issue is not reproducible with latest versions

**Closed by sojanpr** 2015-09-09 17:23 UTC

**Comment by yuliya-tarasenko** [comment] 2016-06-10 12:43
@sojanpr The issue is sometimes reproduced for me as well, but unfortunately there are no specific steps. Sometimes after clicking on the link I also get:
{"+is_first_session":false,"+clicked_branch_link":false}

**Comment by sojanpr** [comment] 2016-06-10 15:25
@yuliya-tarasenko  Sorry that you hit this issue. We will check and update you. Mean time could you please check if the link you are clicking is created by a different Branch key than your app is using. ( For example links created with `TestMode = true` in manifest and app is installed with `TestMode = false`)

**Comment by sojanpr** [comment] 2016-06-10 15:26
@yuliya-tarasenko It would be very helpful if you can share us a link that is having this issue
