### ISSUE TITLE
Urgent: Drop ApacheClient for Marshmellow / Update minSDK to 9

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#123] opened 2015-08-25 18:09 UTC
Because of the [behaviour changes for Android M](https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client) it is now vital to drop the 'org.apache.http.legacy' package. It is no longer included on **Android M** and with good reason.

At the very least:
- Update the minimum SDK to 9. Froyo and below is less than 0.5% (source [1](http://www.statista.com/statistics/271774/share-of-android-platforms-on-mobile-devices-with-android-os/) [2](https://developer.android.com/about/dashboards/index.html))
- Switch to `HttpURLConnection`

Currently, if you build for Android M, the classes will not be found and the app crashes. If you use Proguard, these problems arise compile time.

Work around is module-level `com.android.application` `build.gradle`
````Gradle
android {
    useLibrary 'org.apache.http.legacy'
}
````

Perhaps think about moving over to Volley or OkHttp, since projects that include this library already are using these or even better, provide adapters to use either or none.

**Comment by sojanpr** [comment] 2015-08-28 21:44
@SleeplessByte  Thanks for the notification. We  have already started checking compatibility with Android M and will addressing the changes asap

**Comment by SleeplessByte** [comment] 2015-08-30 14:33
This does not only cover the platform, but also building against API 23, including version 23.X+ of all the support libraries.

**Comment by sojanpr** [comment] 2015-09-10 23:40
@SleeplessByte  PR#136 address this issue https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/pull/136

**Comment by SleeplessByte** [comment] 2015-09-14 21:00
:+1:

**Comment by sdoward** [comment] 2015-10-05 13:45
+1 

Branch branch = Branch.getInstance(); 

returns null on API 23 at the moment

**Comment by sojanpr** [comment] 2015-10-05 17:06
@sdoward  Thank you very much for trying this PR and  the update. 
I couldn't reproduce the issue now. Actually Branch.getInstance() will return null if there is no instance created yet. Could you please help us by check that you have extended you application with `BranchApp` Class.

**Comment by sojanpr** [comment] 2015-10-13 23:39
Closing this issue since 1.8.12 has added the support for Android M

**Closed by sojanpr** 2015-10-13 23:39 UTC
